import { notFound } from "next/navigation";
import { sites } from "../../lib/sites";

export function generateStaticParams() { return sites.map((site) => ({ site: site.slug })); }

export default async function SitePage({ params }: { params: Promise<{ site: string }> }) {
  const { site: slug } = await params;
  const site = sites.find((item) => item.slug === slug);
  if (!site) notFound();
  return <main style={{ "--brand": site.brand, "--accent": site.accent, "--ink": site.ink } as React.CSSProperties} className="template">
    <header className="template-nav"><a className="brand" href="#home"><span>{site.icon}</span>{site.name}</a><nav><a href="#about">About</a><a href="#services">Services</a><a href="#gallery">Gallery</a><a href="#contact">Contact</a></nav><a className="nav-cta" href="#contact">{site.cta}</a></header>
    <section id="home" className="hero"><div className="hero-copy"><p className="eyebrow">{site.tagline}</p><h1>{site.hero}</h1><p>{site.description}</p><div className="actions"><a className="primary-button" href="#contact">{site.cta} <span>→</span></a><a className="text-button" href="#services">Explore services</a></div><div className="trust"><strong>{site.stat}</strong><span>{site.statLabel}</span></div></div><div className="hero-photo" style={{backgroundImage:`linear-gradient(105deg, rgba(10,15,20,.14), rgba(10,15,20,.02)), url(${site.images[0]})`}}><div className="photo-label"><span>✦</span><p>{site.photoCaption}</p></div></div></section>
    <section id="about" className="about section"><div><p className="eyebrow">Our story</p><h2>{site.aboutTitle}</h2></div><div><p className="body-copy">{site.about}</p><div className="mini-stats">{site.miniStats.map(([number,label])=><div key={label}><strong>{number}</strong><span>{label}</span></div>)}</div></div></section>
    <section id="services" className="services section"><div className="section-heading"><p className="eyebrow">What we offer</p><h2>Everything you need, all in one place.</h2></div><div className="service-grid">{site.services.map((service,index)=><article key={service.title} className="service-card"><span>0{index+1}</span><h3>{service.title}</h3><p>{service.text}</p><a href="#contact">Learn more →</a></article>)}</div></section>
    <section id="gallery" className="gallery section"><div className="section-heading"><p className="eyebrow">A closer look</p><h2>Made for the moments that matter.</h2></div><div className="gallery-grid">{site.images.slice(1).map((image,index)=><div key={image} className={`gallery-image image-${index+1}`} style={{backgroundImage:`url(${image})`}}><span>{site.galleryLabels[index]}</span></div>)}</div></section>
    <section className="testimonial"><div className="quote-mark">“</div><blockquote>{site.testimonial.quote}</blockquote><div className="person"><div>{site.testimonial.initials}</div><p><strong>{site.testimonial.name}</strong><br/>{site.testimonial.role}</p></div></section>
    <section className="faq section"><div><p className="eyebrow">Questions, answered</p><h2>Good to know before you visit.</h2></div><div className="faq-list">{site.faq.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
    <section id="contact" className="contact section"><div className="contact-info"><p className="eyebrow">Let’s connect</p><h2>{site.contactTitle}</h2><p>{site.address}<br/>{site.hours}</p><a href={`tel:${site.phone.replace(/\s/g,"")}`}>{site.phone}</a><a href={`mailto:${site.email}`}>{site.email}</a><div className="map"><iframe title={`${site.name} location`} src={`https://www.google.com/maps?q=${encodeURIComponent(site.mapQuery)}&output=embed`} loading="lazy"/></div></div><form action="#contact"><label>Your name<input name="name" placeholder="Jane Smith" required/></label><label>Email address<input name="email" type="email" placeholder="jane@example.com" required/></label><label>How can we help?<textarea name="message" placeholder={site.formPlaceholder} rows={4}/></label><button className="primary-button" type="submit">Send enquiry <span>→</span></button><p className="form-note">We’ll get back to you within one business day.</p></form></section>
    <footer><a className="brand" href="#home"><span>{site.icon}</span>{site.name}</a><p>© 2026 {site.name}. Made with care.</p><a href="#home">Back to top ↑</a></footer>
    <a className="whatsapp" href={`https://wa.me/${site.whatsapp}?text=${encodeURIComponent(`Hello ${site.name}, I’d like to know more.`)}`} target="_blank" rel="noreferrer" aria-label={`Chat with ${site.name} on WhatsApp`}>◔ <span>WhatsApp</span></a>
  </main>;
}
